# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='担当者')),
                ('vender', models.CharField(max_length=255, verbose_name='メーカー')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('cpuinfo', models.CharField(blank=True, max_length=255, verbose_name='CPU')),
                ('meminfo', models.CharField(max_length=255, verbose_name='Memory')),
                ('nicinfo', models.CharField(max_length=255, verbose_name='NIC情報')),
                ('biosinfo', models.CharField(max_length=255, verbose_name='BIOSバージョン')),
            ],
        ),
    ]
