# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_personnel', models.CharField(blank=True, max_length=255, verbose_name='借用担当者')),
                ('borrow_date', models.DateTimeField(verbose_name='借用日')),
                ('borrow_check', models.CharField(choices=[('○', 'OK'), ('-', 'NG')], max_length=2, verbose_name='借用時チェック')),
                ('return_date', models.DateTimeField(verbose_name='返却日')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='biosinfo',
            field=models.CharField(blank=True, max_length=255, verbose_name='BIOSバージョン'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='meminfo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nicinfo',
            field=models.CharField(blank=True, max_length=255, verbose_name='NIC情報'),
        ),
    ]
