# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.CharField(max_length=255, verbose_name='メーカー')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('cpuinfo', models.CharField(max_length=255, verbose_name='CPU')),
                ('meminfo', models.CharField(max_length=255, verbose_name='Memory')),
                ('nicinfo', models.CharField(max_length=255, verbose_name='NIC情報')),
                ('biosinfo', models.CharField(max_length=255, verbose_name='BIOSバージョン')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
