# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_auto_20170903_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinery',
            name='author',
            field=models.CharField(max_length=255, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='machinery',
            name='cpuinfo',
            field=models.CharField(blank=True, max_length=255, verbose_name='CPU'),
        ),
    ]
